//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumerGuideApp.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Companies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Companies()
        {
            this.Services = new HashSet<Services>();
        }
    
        public int CompanyID { get; set; }
        public string Name { get; set; }
        public string Grade { get; set; }
        public string Address { get; set; }
        public string Phone { get; set; }
        public Nullable<int> SpecializationID { get; set; }
        public Nullable<int> OwnershipTypeID { get; set; }
        public string WorkingHours { get; set; }
        public string WorkingDays { get; set; }
    
        public virtual OwnershipTypes OwnershipTypes { get; set; }
        public virtual Specializations Specializations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Services> Services { get; set; }
    }
}
